language: node_js
node_js:
  - "7.7.1"
cache:
  directories:
    - $HOME/.npm  
branches:
  only:
  - master
install:
  - npm install
script:
  - npm run start
  - ./node_modules/gulp/bin/gulp.js remove-dead-css
after_success:
  - ./node_modules/gulp/bin/gulp.js deploy  